//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CpuTrayApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CpuTrayApp.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Speed.
        /// </summary>
        internal static string Menu_CpuSpeed {
            get {
                return ResourceManager.GetString("Menu_CpuSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum CPU Limit.
        /// </summary>
        internal static string Menu_MaxCpuLimit {
            get {
                return ResourceManager.GetString("Menu_MaxCpuLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum CPU Limit.
        /// </summary>
        internal static string Menu_MinCpuLimit {
            get {
                return ResourceManager.GetString("Menu_MinCpuLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Plans.
        /// </summary>
        internal static string Menu_PowerPlans {
            get {
                return ResourceManager.GetString("Menu_PowerPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Tray Utility.
        /// </summary>
        internal static string Tray_Title {
            get {
                return ResourceManager.GetString("Tray_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Update_Cancel {
            get {
                return ResourceManager.GetString("Update_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Update_Confirm {
            get {
                return ResourceManager.GetString("Update_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to check for updates..
        /// </summary>
        internal static string Update_Error {
            get {
                return ResourceManager.GetString("Update_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available: {0} Current version: {1} Would you like to open the GitHub page to download it?.
        /// </summary>
        internal static string Update_NewVersionAvailable {
            get {
                return ResourceManager.GetString("Update_NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        internal static string Update_Title {
            get {
                return ResourceManager.GetString("Update_Title", resourceCulture);
            }
        }
    }
}
